name: Gen podcast feed
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout repo
        uses: actions/checkout@v3
      - name: Run Feed Gen
        uses: Source888/podcasts-gen@main
