name: Gen podcast feed
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout repo
        uses: actions/checkout@v3
      - name: Setup py
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
      - name: Install deped
        run: | 
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Run generator
        run: python feed.py
      - name: Push repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Modified feed"
          git push
